modLoader="javafml" 
loaderVersion="[44,)" 
license="MIT"
[[mods]] 
modId="mchalo" 
version="${file.jarVersion}" 
displayName="MCHalo" 
logoFile="icon.png"
authors="AzureDoom"
description='''
Adds weapons from the Halo franchise to Minecraft!
'''
[[dependencies.mchalo]] 
    modId="forge" 
    mandatory=true 
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mchalo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mchalo]]
    modId="azurelib"
    mandatory=true
    versionRange="[1.0.2,)"
    ordering="NONE"
    side="BOTH"

